package com.aireplyassistant.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF1F41BB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDCE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001159)
val md_theme_light_secondary = Color(0xFF6200EE)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEADDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF21005E)
val md_theme_light_tertiary = Color(0xFF03DAC6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB0F9F1)
val md_theme_light_onTertiaryContainer = Color(0xFF00201D)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFDCE1FF)
val md_theme_dark_onPrimary = Color(0xFF002B82)
val md_theme_dark_primaryContainer = Color(0xFF003AB1)
val md_theme_dark_onPrimaryContainer = Color(0xFFDCE1FF)
val md_theme_dark_secondary = Color(0xFFEADDFF)
val md_theme_dark_onSecondary = Color(0xFF3800B3)
val md_theme_dark_secondaryContainer = Color(0xFF5300E1)
val md_theme_dark_onSecondaryContainer = Color(0xFFEADDFF)
val md_theme_dark_tertiary = Color(0xFF80F7EE)
val md_theme_dark_onTertiary = Color(0xFF00403D)
val md_theme_dark_tertiaryContainer = Color(0xFF005B57)
val md_theme_dark_onTertiaryContainer = Color(0xFFB0F9F1)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE7E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE7E1E6)
